apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: localsecretstore
 #namespace: production namespace will be option
spec:
  type: secretstores.aws.secretmanager
  version: v1
  metadata:
  - name: region
    value: ""
  - name: accessKey
    value: ""
  - name: secretKey
    value: ""