apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: pubsub  
 #namespace: production namespace will be option
spec:
  type: pubsub.azure.servicebus
  version: v1
  metadata:
  - name: connectionString
    value: ""
	