apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: localsecretstore
 #namespace: production namespace will be option
spec:
  type: secretstores.azure.keyvault
  version: v1
  metadata:
  - name: vaultName 
    value: ""
  - name: azureEnvironment 
    value: ""
  - name: azureTenantId
    value: ""
  - name: azureClientId
    value: ""
  - name: azureClientSecret
    value : ""