apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: localsecretstore 
 #namespace: production namespace will be option
spec:
  type: secretstores.local.file
  version: v1
  metadata:
  - name: secretsFile
    value: "" # file name like azureSecrets.json
  - name: nestedSeparator
    value: ":"