apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: statestorenosql
 #namespace: production namespace will be option
spec:
  type: state.redis
  version: v1
  metadata:
  - name: redisHost
    value: # host will be local port of redis localhost:6379
  - name: redisPassword
    value: ""