apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: statestore
 #namespace: production namespace will be option
spec:
  type: state.redis
  version: v1
  metadata:
  - name: redisHost
    value: # host will be local port of redis localhost:6379
  - name: redisPassword
    value: ""
  - name: actorStateStore
    value: "" # value must be true or false